id: P003237
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 2021-12-17 10:49:26.247560
source_metadata:
  id: bdr:W30126
  title: དཔལ་ལྡན་གསོ་བ་རིག་པའི་ཁོག་འབུག་ལེགས་བཤད་བཻཌཱུརྱའི་མེ་ལོང་དྲང་སྲོང་དགྱེས་པའི་དགའ་སྟོན
  author: ''
  volumes:
    395c954391374af8803b5dd61ead0584:
      image_group_id: I5887
      title: ''
      volume_number: 1
      total_pages: 598
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
