id: P003237
initial_creation_type: ocr
source_metadata:
  id: bdr:W30126
  title: དཔལ་ལྡན་གསོ་བ་རིག་པའི་ཁོག་འབུག་ལེགས་བཤད་བཻཌཱུརྱའི་མེ་ལོང་དྲང་སྲོང་དགྱེས་པའི་དགའ་སྟོན
  author: ''
  volumes:
    395c954391374af8803b5dd61ead0584:
      image_group_id: I5887
      title: ''
      volume_number: 1
      total_pages: 598
