id: opecha:P003237
initial_creation_type: ocr
source_metadata:
  id: bdr:W30126
  title: དཔལ་ལྡན་གསོ་བ་རིག་པའི་ཁོག་འབུག་ལེགས་བཤད་བཻཌཱུརྱའི་མེ་ལོང་དྲང་སྲོང་དགྱེས་པའི་དགའ་སྟོན
  volume: ''
  author: ''
