id: I9F669169
legacy_id: P003237
ocr_import_info:
  bdrc_scan_id: W30126
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T07:58:41'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-03T11:19:02.658766+00:00'
last_modified: 2022-09-03 19:19:19.770901
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W30126
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW30126
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དཔལ་ལྡན་གསོ་བ་རིག་པའི་ཁོག་འབུག་ལེགས་བཤད་བཻཌཱུརྱའི་མེ་ལོང་དྲང་སྲོང་དགྱེས་པའི་དགའ་སྟོན།
  author: སྡེ་སྲིད་སངས་རྒྱས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.7018664112663457
  ocr_word_median_confidence_index: 0.7799999713897705
quality: null
bases:
  I5887:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5887
      total_pages: 598
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5887.txt
    statistics:
      ocr_word_median_confidence_index: 0.7799999713897705
      ocr_word_mean_confidence_index: 0.7018664112663457
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
